language: python

# Run tox with python 3.4, but let _it_ build the envs for the various Python
# versions (instead of Travis)
python: 3.4

env:
  matrix:
    - TOXENV=py27 PIP="-U pip"
    - TOXENV=py34 PIP="-U pip"
    - TOXENV=py34 PIP="pip==6.1.1"
    - TOXENV=py34 PIP="pip==1.5.6"

install:
  - travis_retry pip install tox
  - travis_retry pip install $PIP

script:
  - tox
